[postgresql_admin]
# Used by setup_pmi_database.py to create the new DB
# This user MUST have CREATE DATABASE permissions
host = localhost
port = 5432
user = postgres
password = postgres
dbname = postgres

[pmi_database]
# Used by Flask app and scripts to access the PMI data
host = localhost
port = 5432
user = postgres
password = postgres
dbname = pmi

[ehrbase_api]
# Used by Flask app and install_templates.py
base_url = http://localhost:8080/ehrbase/rest/openehr/v1
user = ehrbase-user
password = ehrbase-password

[openehr]
patient_id_namespace = uk_nhs_nhs_number
